#!/bin/sh
# Copyright 2016 The dev Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

declare glb_version="1.4"

# Run-state:
# 0:Not-run(readonly)
# 1:Run(alterable,local,default)
# 2:Run(readonly,local)
# 3:Run(readonly,remote)
declare -g glb_run=1 glb_run_dry=0 glb_run_sudo=0 glb_run_daemon=0

# Command file
declare -g glb_file glb_func glb_argv glb_user glb_dest glb_sta=0 glb_etr="command"

# For option arguments
declare -Ag glb_run_nodes opa_rem opa_als

#
# Usage information.
#
dev_help_usage() {
    declare files="<cmd-file>"
    [ ! -z "$1" ] && files="$1"

    echo "Usage: dev [--[options [args]]] [prj] $files <cmd-func> [cmd-args] ..."
    echo "       dev [--[options [args]]] [args] ..."; echo
}

#
# List all options
#
dev_help_options() {
    echo "Optional arguments:"; echo
    dev_help_options_items |sort; echo
}

#
# List all options
#
dev_help_options_items() {
    declare opt sht als

    for als in "${!opa_als[@]}"; do
        opt="${opa_als[$als]}"
        [ "$opt" != "$als" ] && sht=", -$als" || sht=""
        echo -e "  --${opt//_/-}$sht \t ${opa_rem[$opt]}"
    done

    # for i in $(compgen -A function); do
    #     if [[ "${i:0:8}" == "opa_fun_" ]]; then
    #         opt="${i:8}"
    #     fi
    # done
}

#
# Usage:
#     dev_help_projects
#
dev_help_projects() {
    declare ret prj wkdir

    if [ "$glb_prj" == "dev" ]; then
        wkdir=$glb_base
        if [ -z $glb_file ]; then
            # List all projects
            echo "These are the all aviliable <prj>s:"; echo
            for prj in "${!cfg_projects[@]}"; do
                ret="$ret $prj"
            done
            echo ${ret:1} |tr " " "\n" |column -c $(tput cols) |fmt; echo
        fi
    else
        wkdir=$glb_wkdir
    fi

    if [ -z $glb_file ]; then
        # List files in project
        dev_help_files $wkdir
    else
        # List all cmd-func
        dev_help_functions $wkdir $1
    fi
}

#
# List all command files.
#
dev_help_files() {
    declare wkdir
    [ -z "$1" ] && wkdir="$glb_wkdir" || wkdir="$1"
    [ -z $wkdir ] && return 0
    echo "These are the all aviliable <cmd-file>s:"; echo

    declare ret
    ret="$ret $(dev_cmd_files $wkdir/cmd)"
    echo ${ret:1} |tr " " "\n" |column -c $(tput cols) |fmt; echo
}

#
# List all functions of included <cmd-file>s.
#
dev_help_functions() {
    declare wkdir
    [ -z "$1" ] && wkdir="$glb_wkdir" || wkdir="$1"
    echo "These are the all aviliable <cmd-func>s:"; echo

    for i in $(compgen -A function); do
        if [[ "${i:0:4}" == "cmd_" ]]; then
            echo -e "  ${i:4} \t in $wkdir/cmd/$glb_file:$i()"
        fi
    done

    echo
}

#
# Usage:
#     dev_load_files <prj> <cmd-file>
#
dev_load_files() {
    declare wkdir="$1" cf="$2"
    [ -f $wkdir/lib/bootstrap ] && . $wkdir/lib/bootstrap
    [ -f $wkdir/etc/dev.cmd/$cf.conf ] && . $wkdir/etc/dev.cmd/$cf.conf
    [ -f $wkdir/cmd/$cf.var ] && . $wkdir/cmd/$cf.var
    [ ! -f $wkdir/cmd/$cf.sh ] && return 1 || . $wkdir/cmd/$cf.sh
}

#
# Recursively process subdirectories
#
dev_cmd_files() {
    for i in $(ls $1); do
        if [[ -d $1/$i ]]; then
            dev_cmd_files $1/$i $i/
        elif [[ "${i: -3}" == ".sh" ]]; then
            echo "$2${i:0:-3}"
        fi
    done
}

#
# Usage:
#     dev_scp <user-host> <command>
#
dev_scp() {
    declare cmd="scp -i $glb_ssh_key -o StrictHostKeyChecking=no $@"
    echo "$cmd" && $cmd
}

#
# Usage:
#     dev_ssh <user-host> <command>
#
dev_ssh() {
    declare cmd="ssh -i $glb_ssh_key -o StrictHostKeyChecking=no $@"
    echo "$cmd" && $cmd
}

#
# Usage:
#     dev_dnf
#
dev_dnf() {
    # -4     Resolve to IPv4 addresses only.
    # --allowerasing
    #        Allow  erasing  of  installed  packages  to  resolve dependencies.
    declare cmd="sudo dnf -y --allowerasing -4 $@"
    echo "$cmd" && $cmd
}

#
# Usage:
#     dev_prj <prj>
#
dev_prj() {
    [[ ! -z "$glb_prj" ]] && return 1

    if [ "$1" == "dev" ]; then
        declare -gr glb_prj="dev" glb_wkdir=$glb_base; return 0
    fi

    if [ $# -ge 1 ] && [ -n "${cfg_projects[$1]+1}" ]; then
        declare -gr glb_prj="$1" glb_wkdir=${cfg_projects[$1]}; return 0
    fi

	declare -gr glb_prj="dev" glb_wkdir=$glb_base; return 1
}

#
# Prepare command files
# Usage:
#     dev_file <cmd-file>
#
dev_file() {
    [ ! -z "$glb_file"] && return 1

    if [[ $# -le 0 || -z "$1" ]]; then
        dev_help_projects >&2; return 1
    fi

    if ! dev_load_files $glb_wkdir $1; then
        echo "Command file not found: $glb_wkdir/cmd/$1.sh" >&2; return 1
    fi

    glb_file="$1"; return 0
}

#
# Set execution function
#
dev_func() {
    if [ ! -z "$glb_func" ]; then
        echo "Error: \$glb_func has a value: $glb_func" >&2; return 1
    fi

    # File is command(stand alone)
    if [ "$glb_sta" -gt 0 ]; then
        glb_func="cmd_main"; return 1
    fi

    if [[ $# -le 0 || -z "$1" ]]; then
        echo "Missing command function" >&2; echo >&2; dev_help_functions >&2; return 1
    fi

    declare func=${1/-/_}

    [[ "${func:0:4}" == "cmd_" || -z "$glb_file" ]] || func="cmd_$func"
    if [[ "$(declare -F $func)" != "$func" ]]; then
        echo "Command not found: $func" >&2; return 1
    fi

    glb_func="$func"
}

#
# Set run state
# Run-state:
# 0:Not-run(readonly)
# 1:Run(alterable,local,default)
# 2:Run(readonly,local)
# 3:Run(readonly,remote)
#
dev_run() {
    if [[ "$glb_run" -eq 1 ]]; then
        glb_run="$1" return 0
    else
        echo "Error: \$glb_run has a value: $glb_run" >&2; return 1
    fi
}


#
# Execute a command from all nodes.
# Usage:
#     dev_exec_remote dev [options] <cmd-file> <cmd-func> [cmd-args]
#
dev_exec_remote() {
    if [[ "${#glb_run_nodes[@]}" -le 0 ]]; then
        echo "Nodes is empty" >&2; return 1
    fi

    declare cmd user host

    for host in "${!glb_run_nodes[@]}"; do
        user="${glb_run_nodes[$host]}"
        cmd="ssh -i $glb_ssh_key -o StrictHostKeyChecking=no $user@$host"
        [ $glb_run_sudo -eq 1 ] && cmd="$cmd sudo"

        set +o errexit
        dev_exec $host $user $cmd $@
        set -o errexit

        echo
    done
}

#
# Usage:
#     dev_exec_local <command> <arguments>...
#
dev_exec_local() {
    declare host="127.0.0.1" user="$(whoami)" cmd
    cmd="$host $user"
    [ $glb_run_sudo -eq 1 ] && cmd="$cmd sudo $glb_base/bin/dev $glb_prj $glb_file"
    dev_exec $cmd $@
}

#
# Usage:
#     dev_exec <host> <user> <command> <arguments>...
#
dev_exec() {
    declare cmd log_out
    declare host="$1"; shift
    declare user="$1"; shift
    declare desc="[$user@$host $(date '+%Y-%m-%d %H:%M:%S')]"

    log_out="$glb_wkdir/var/log/$host.log"

    cmd="$@"

    echo "$desc" >>$log_out
    echo "$cmd"; echo "$cmd" >>$log_out
    chmod a+wx $log_out

    [ $glb_run_dry -eq 1 ] && return 0

    if [ $glb_run_daemon -eq 1 ]; then
        nohup $cmd >>$log_out 2>&1 &
        echo "PID: $!"
    else
        $cmd 2>&1 | tee -a $log_out
    fi
}

